/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EscrowFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allEscrows"
      | "companyEscrows"
      | "createEscrow"
      | "escrowToCompany"
      | "getAllEscrows"
      | "getCompanyEscrows"
      | "getEscrowCompany"
      | "getEscrowCount"
      | "getEscrowDetails"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "EscrowCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "allEscrows",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "companyEscrows",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowToCompany",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEscrows",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCompanyEscrows",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrowCompany",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrowCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrowDetails",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "allEscrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "companyEscrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowToCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllEscrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCompanyEscrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEscrowCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEscrowCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEscrowDetails",
    data: BytesLike
  ): Result;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    escrowAddress: AddressLike,
    company: AddressLike,
    targetAmount: BigNumberish,
    deadline: BigNumberish,
    timestamp: BigNumberish,
    campaignName: string,
    campaignDescription: string,
    wishlistItemId: string
  ];
  export type OutputTuple = [
    escrowAddress: string,
    company: string,
    targetAmount: bigint,
    deadline: bigint,
    timestamp: bigint,
    campaignName: string,
    campaignDescription: string,
    wishlistItemId: string
  ];
  export interface OutputObject {
    escrowAddress: string;
    company: string;
    targetAmount: bigint;
    deadline: bigint;
    timestamp: bigint;
    campaignName: string;
    campaignDescription: string;
    wishlistItemId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowFactory extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowFactory;
  waitForDeployment(): Promise<this>;

  interface: EscrowFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allEscrows: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  companyEscrows: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  createEscrow: TypedContractMethod<
    [
      _company: AddressLike,
      _masterWallet: AddressLike,
      _targetAmount: BigNumberish,
      _durationInDays: BigNumberish,
      _campaignName: string,
      _campaignDescription: string,
      _wishlistItemId: string
    ],
    [string],
    "nonpayable"
  >;

  escrowToCompany: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getAllEscrows: TypedContractMethod<[], [string[]], "view">;

  getCompanyEscrows: TypedContractMethod<
    [_company: AddressLike],
    [string[]],
    "view"
  >;

  getEscrowCompany: TypedContractMethod<
    [_escrow: AddressLike],
    [string],
    "view"
  >;

  getEscrowCount: TypedContractMethod<[], [bigint], "view">;

  getEscrowDetails: TypedContractMethod<
    [_escrow: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean, boolean, string, string] & {
        company: string;
        totalRaised: bigint;
        targetAmount: bigint;
        deadline: bigint;
        isFinalized: boolean;
        isSuccessful: boolean;
        campaignName: string;
        campaignDescription: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allEscrows"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "companyEscrows"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [
      _company: AddressLike,
      _masterWallet: AddressLike,
      _targetAmount: BigNumberish,
      _durationInDays: BigNumberish,
      _campaignName: string,
      _campaignDescription: string,
      _wishlistItemId: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "escrowToCompany"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getAllEscrows"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCompanyEscrows"
  ): TypedContractMethod<[_company: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getEscrowCompany"
  ): TypedContractMethod<[_escrow: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEscrowCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEscrowDetails"
  ): TypedContractMethod<
    [_escrow: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean, boolean, string, string] & {
        company: string;
        totalRaised: bigint;
        targetAmount: bigint;
        deadline: bigint;
        isFinalized: boolean;
        isSuccessful: boolean;
        campaignName: string;
        campaignDescription: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;

  filters: {
    "EscrowCreated(address,address,uint256,uint256,uint256,string,string,string)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
  };
}
